# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute the empirical distribution using Rcpp
#' @description Find optimal coupling using KM algorithm
#' @param G the nxn matrix of transport cost(i.e. Riemannian distance)
#' @param v a integer vector with length n
#' @return the optimal coupling expressed by permutation of 1..n
#' @export
opt_coupling <- function(G, v) {
    .Call('_SphRankSign_opt_coupling', PACKAGE = 'SphRankSign', G, v)
}

